### ISSUE TITLE
`set-output` command is deprecated

### ISSUE THREAD

**Issue by starverdiyev** [tokorom/action-slack-incoming-webhook#37] opened 2022-11-16 07:18 UTC
After running action, I see warning:

`Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/`

Will be PR for this?

Thanks!

**Comment by dadajam4** [comment] 2023-01-11 11:12
I encountered the same problem.

**Comment by joltcoke** [comment] 2023-01-11 11:16
Are you sure this is still a problem? AFAIK this should be fixed by 4e7e57a329606be7cf6113f5d66a202833e040e5

**Comment by starverdiyev** [comment] 2023-01-11 11:22
I use this actions with main branch, like : `tokorom/action-slack-incoming-webhook@main` and still got this warning.

**Comment by joltcoke** [comment] 2023-01-11 17:53
Indeed. The problem is that there is no new build. I've opened PR #40 to address this.

**Comment by tokorom** [comment] 2023-01-12 08:39
@joltcoke Thanks!

Merged the pull request into the main branch and released as v1.3.0.

**Closed as completed** 2023-09-20 02:00 UTC
